# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

default:
  image: hoijui/nim-ci:latest

build:
  before_script:
  - git submodule update --init --recursive
  script:
  - echo "PATH:"
  - echo "$PATH"
  - echo AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  - echo "$PATH" | grep nimble
  - echo BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  - ls "$HOME/.nimble/bin/"
  - bash -x scripts/ci-run
  only:
    - master
  artifacts:
    paths:
    - public
