# SPDX-FileCopyrightText: 2022 - 2023 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

# Defines a GitHub (GH) Action, to be used in GH CI pipelines

name: 'OSH Linter/Analyzer'
description: 'Runs "osh check", which analyzes an Open Source Hardware repository, indicating how well it adheres to our set of rules.'
inputs:
  repo-path:  # id of input
    description: 'Path to the repo that should be analyzed (default: ".")'
    required: true
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - 'report_gen'
    - '-C'
    - ${{ inputs.repo-path }}
    - '--download-badges'
