#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

# Exit immediately on each error and unset variable;
# see: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail
#set -Eeu

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
proj_dir="$(cd "$script_dir"/..; pwd)"
build_dir="$proj_dir/build"
package_dir="$proj_dir/public"
nim_win_version="1.4.8"
# NOTE: NIM_WIN_DIR should be set by the CI container (hoijui/ci-nim:latest)
nim_win_dir="${NIM_WIN_DIR:-$build_dir/nim-${nim_win_version}}"
sudo=$(which sudo && echo "sudo" || echo "")

if [ -z "$(find "$proj_dir" -name '*.nimble')" ]
then
	>&2 echo "ERROR: please run this script from the project root directory (containing the .nimble file)!"
	exit 1
fi

function version() {
	git describe \
		--tags \
		--dirty \
		--broken \
		--always \
		--long \
		--candidates=99 \
		--first-parent
}

function print_help() {

	echo "Run all we want to be done in our CI."
	echo
	echo "Usage:"
	echo "         $(basename "$0") [OPTIONS]"
	echo "Options:"
	echo "          -h, --help                  Show this help message"=
	echo "          -s, --install-requirements  Install whatever this script needs to run (works only on Debian/Ubuntu)"
}

function install_requirements() {

	apt_updated=false
	if ! which git > /dev/null || ! which x86_64-w64-mingw32-gcc > /dev/null
	then
		echo "Install pre-requisites ..."
		if ! $apt_updated
		then
			$sudo apt-get update
			apt_updated=true
		fi
		$sudo apt-get install -y -qq curl git # > /dev/null
	fi
	if ! which pandoc > /dev/null
	then
		echo "Install pandoc ..."
		if ! $apt_updated
		then
			$sudo apt-get update
			apt_updated=true
		fi
		$sudo apt-get install -y -qq pandoc # > /dev/null
	fi

	mkdir -p "$build_dir"
	cd "$build_dir"

	if ! which nimble > /dev/null
	then
		echo "Install nim and nimble ..."
		curl "https://nim-lang.org/choosenim/init.sh" \
			--output "choosenim_init.sh" \
			-sSf
		$sudo sh choosenim_init.sh -y
	fi

	# Fetch cross-compile requirements
	if ! which x86_64-w64-mingw32-gcc > /dev/null
	then
		echo "Install the win64 cross-compiler ..."
		if ! $apt_updated
		then
			$sudo apt-get update
			apt_updated=true
		fi
		$sudo apt-get install -y -qq mingw-w64 # > /dev/null
	fi
	if ! [ -d "$nim_win_dir" ] > /dev/null
	then
		echo "Download and extract the nim-win64 package (required for the contained libraries) ..."
		nim_win_arch="nim-${nim_win_version}_x64.zip"
		curl "https://nim-lang.org/download/$nim_win_arch" \
			--output "$nim_win_arch" \
			-sSf
		unzip "$nim_win_arch"
	fi

	cd "$proj_dir"

	echo "Checkout all project sub-modules ..."
	git submodule update --init --recursive

	echo "done."
}

# read command-line args
POSITIONAL=()
while [[ $# -gt 0 ]]
do
	arg="$1"
	shift # past argument

	case "$arg" in
		-h|--help)
			print_help
			exit 0
			;;
		-s|--install-requirements)
			install_requirements
			exit 0
			;;
		*) # non-/unknown option
			POSITIONAL+=("$arg") # save it in an array for later
			;;
	esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

if ! [ -f "$nim_win_dir/bin/libcrypto-1_1.dll" ]
then
	>&2 echo "ERROR: Missing windows nim. Please download it (to the build directory) with '$0 --install-requirements'."
	exit 1
fi

echo
echo "Compiling the software for Linux ..."
nimble -y build

echo
echo "Cross-compiling the software for Windows 64 ..."
nimble -y build \
	--os:windows \
	--cpu:amd64 \
	--gcc.exe:/usr/bin/x86_64-w64-mingw32-gcc \
	--gcc.linkerexe:/usr/bin/x86_64-w64-mingw32-gcc \
	-d:release \
	--app:console \
	--opt:size \
	--passL:-static \
	--opt:speed \
	--embedsrc \
	--threads:on \
	--checks:on

bin_win="$(find "$build_dir" -maxdepth 1 -type f -name '*.exe' -printf '%P\n')"
bin_lin="${bin_win%.exe}"

echo
echo "State after building:"
find "$build_dir"

echo
echo "Moving the binaries to the package dir '$package_dir' ..."
rm -Rf "$package_dir"
mkdir -p "$package_dir"
mkdir "$package_dir/linux64"
mkdir "$package_dir/win64"
cp "$build_dir/$bin_lin" "$package_dir/linux64/"
cp "$build_dir/$bin_win" "$package_dir/win64/"
cp "$nim_win_dir/bin/"{libcrypto-1_1,libcrypto-1_1-x64,libssl-1_1,libssl-1_1-x64,pcre64}.dll "$package_dir/win64/"

echo
echo "Create static documentation ..."
{
	echo '---'
	echo "title: $bin_lin - List of checks"
	echo '---'
	echo
	"$build_dir/$bin_lin" --list-checks --quiet
} > "$package_dir/checks.md"
{
	echo '---'
	echo "title: $bin_lin - "'Output of `'"$bin_lin"' --help`'
	echo '---'
	echo
	echo '```'
	"$build_dir/$bin_lin" --help
	echo '```'
} > "$package_dir/help.md"
css="https://fonts.googleapis.com/css?family=Rock+Salt"
echo '
tbody tr:nth-child(odd) {
	background-color: #dddddd;
}

tbody tr:nth-child(even) {
	background-color: #cccccc;
}

table {
	background-color: #dddddd;
}
' > "$package_dir/table.css"
for md in "$package_dir/"*.md
do
	html="${md%.md}.html"
	pandoc -s --css "$css" --css "table.css" -o "$html" "$md"
done

echo
echo "State after package preparation:"
find "$package_dir"

cd "$package_dir"

echo
echo "Creating the binary archives ..."
version="$(version)"
pkg_lin="${bin_lin}-${version}-x86_64-linux"
pkg_win="${bin_lin}-${version}-x86_64-windows"
mv linux64 "$pkg_lin"
mv win64 "$pkg_win"
zip -r "$pkg_lin".zip "$pkg_lin"
zip -r "$pkg_win".zip "$pkg_win"

img_src_linux="https://icons.iconarchive.com/icons/dakirby309/simply-styled/128/OS-Linux-icon.png"
img_src_windows="https://icons.iconarchive.com/icons/tatice/operating-systems/256/Windows-icon.png"
img_src_archive="https://icons.iconarchive.com/icons/zerode/plump/128/Folder-Archive-zip-icon.png"

echo
echo "Creating HTML ('index.html') that links to all the files generated above ..."
{
	echo "<html>"
	echo '<head>'
	echo '<title>osh-tool - Downloads</title>'
	echo '</head>'
	echo "<body>"
	echo 'Downloadable, generated files from the <a href="https://gitlab.com/OSEGermany/osh-tool">osh-tool repo</a>.'
	echo "<ul>"
	# Create HTML links to all the archive files
	for file in *.zip
	do
		img_src=''
		if [ "$file" = "${pkg_lin}.zip" ]
		then
			img_src="$img_src_linux"
		elif [ "$file" = "${pkg_win}.zip" ]
		then
			img_src="$img_src_windows"
		else
			img_src="$img_src_archive"
		fi
		echo "<li><img alt=\"os_icon\" width=\"64\" src=\"$img_src\"/><a href=\"$file\">$file</a></li>"
	done
	for file in *.md *.html
	do
		if [ "$file" = "index.html" ]
		then
			continue
		fi
		echo "<li><a href=\"$file\">$file</a></li>"
	done
	echo "</ul>"
	echo "</body>"
	echo "</html>"
} >> index.html

cd "$proj_dir"
echo "done."
