#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2023 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

# Exit immediately on each error and unset variable;
# see: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail
#set -Eeu

#script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
#source "$script_dir/env"

nim doc \
	--project \
	--index:on \
	--outdir="build/doc" \
	--git.url="https://github.com/hoijui/osh-tool" \
	--git.commit="master" \
	"src/main.nim"
