#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

# Exit immediately on each error and unset variable;
# see: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail
#set -Eeu

#script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
#source "$script_dir/env"

# We run all tests, even if some are failing.

tests=0
failures=0

function _report_test_res() {
  res="$1"
  echo -n "TEST: "
  if [ "$res" -eq 0 ]
  then
    echo "succeeded."
  else
    echo "failed."
  fi
}

echo
echo
echo 'TEST: "nimble check" ...'
failed=0
nimble check || failed=1
failures=$((failures + failed))
tests=$((tests + 1))
_report_test_res "$failed"

echo
echo
echo 'TEST: "nimble test" ...'
failed=0
nimble test || failed=1
failures=$((failures + failed))
tests=$((tests + 1))
_report_test_res "$failed"

echo
echo
echo "Successful tests: $((tests - failures))/$tests"
if [ $failures -eq 0 ]
then
  echo "All tests successfull!"
else
  >&2 echo "There were test failures!"
fi

exit $failures
